# Generated by Django 5.0 on 2024-02-06 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0004_rename_anio_juegosps4_año_juegosps4_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juegosps5',
            old_name='anio',
            new_name='año',
        ),
        migrations.AddField(
            model_name='juegosps5',
            name='descripcion',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juegosps5',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='juegosps5',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesPS5'),
        ),
    ]
